### PR TITLE
Polishing data, dots, details

### PR DESCRIPTION
**Pull request by jennybc**
A few copy edits, plus one slightly bigger rearrangement.

### CODE REVIEW

**Comment by hadley** [comment]
Thanks! 

How does this length feel to you? It's a fairly simple pattern, but do you think it needs more justification? Other examples?

**Comment by jennybc** [comment]
I think the length is good.

We don't currently include an example of the direct danger in "data via dots, then details":

``` r
sum(1, 1, 1, na.omit = TRUE)
#> [1] 4
```

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

But maybe you're covering that elsewhere.

**Comment by hadley** [comment]
Oh that's a good example to add too

**Comment by hadley** [comment]
Oh actually that's a slightly different case which can go in to data-dots

**Pull request merged**
