### PR TITLE
Name repair

### LINKED ISSUE #4: Vector names
When we munge names (or refrain from doing so) and exactly how.

Most recent group discussion of name repair:

https://github.com/tidyverse/tibble/issues/217

Which lead to `tibble::set_tidy_names()`, `tibble::tidy_names()` in this PR:

https://github.com/tidyverse/tibble/pull/248

### PR DESCRIPTION
**Pull request by jennybc**
Closes #4 Vector names

This should just gestate here as tibble nears release. But I wanted to begin the process of moving the policy stuff out of the tibble docs, since this might have relevance beyond tibble.

@krlmlr I take responsibility for keeping this up-to-date with tibble. I will soon make the inverse PR and remove this content from the `name-repair` help in tibble.

### CODE REVIEW

**Comment by krlmlr** [comment]
We still need to disambiguate "syntactic" vs. "syntactic + unique". I'm deeply in love with "semantic" as a synonym for the latter, to me it fits the description of names that can be used unambiguously without quotes. Would you like to suggest an alternative?

**Comment by jimhester** [comment]
I think enough people get syntax and semantics confused when talking about programming languages it would be better to come up with an alternative term, but I don't have a suggestion of one. /end unhelpful comment.

**Comment by lionel-** [comment]
Perhaps identifying names? Shorthand: identifiers.

**Comment by lionel-** [comment]
Seems nice especially since we often use the data frame as a scope.

**Comment by jennybc** [comment]
"syntactique"

**Comment by jennybc** [comment]
"identifying" and "identified" have real advantages. I wish they didn't have so many syllables, though.

**Comment by krlmlr** [comment]
Maybe "synique", as suggested earlier by Jenny? It's pretty rare on GitHub: https://github.com/search?q=synique, but otherwise refers to a double-safety razor (among other things).

Let's keep looking for better alternatives too.

**Comment by jennybc** [comment]
I'm starting to think "synique" is our best bet. I might make a PR here and on tibble with that. It's better than the *status quo* (the confusing use of "syntactic").

Note: @hadley seems ok with "semantic".

I agree with @batpigandme and @jimhester, though, ... there's existing fog around syntax vs. semantics and we probably don't want to go there.

**Comment by batpigandme** [comment]
In the semantic scheme, is semantic supposed to be syntactic+? I like synique/syntatique just because it comes off as related to, but somehow more than syntactic. I think the idea as you laid it out, Jenny, of three levels of name repair is comprehensible in a manner such that, as long as the sequence is clear, the names themselves don't have to be terribly evocative.

**Comment by jimhester** [comment]
If the only alternative is to make up a name I would much rather use "semantic".

**Comment by jennybc** [comment]
No, "standard" is new. Ironically, "standard" names are what's needed for functions that use nonstandard evaluation 😅.

I think this is the core issue re: why this is hard:

  * "syntactic" is a property that applies to an individual name. Making a name syntactic has nothing to with context, i.e. the other names.
  * This thing we might call synique/semantic/standard/whatever is a property of a **set** of names.

**Comment by jennybc** [comment]
We've always got "tidy" to fall back on, actually.

**Comment by hadley** [comment]
TBH, I like "tidy" best out of all the options.

**Comment by echasnovski** [comment]
I don't mean to pry into the internal tidyverse business, but I just happened to read this thread and have couple of suggestions.

I tried to rephrase the essense of "syntactic + unique" and ended up with "can be used *directly* in tidyverse NSE, i.e. dplyr/ggplot2 code". It seems to be accurate as non-unique names can't be used there and non-syntactic unique can't be used *directly*. This gave a candidate **"direct names"**. For me it also seems to have an association with "names that have necessary qualities".

A little elaborating also gave two alternatives: **"clean names"** and **"neat names"**, which are both happen to be close to "tidy".

Hope that helps.

**Comment by jennybc** [comment]
@echasnovski Yeah, it's fruitful to push hard on the "can be used anywhere" angle. It's not even tidyverse-specific. This quality of "syntactic and unique" is necessary for any function that uses NSE, including `$` or `base::subset()`.

Free associating on this theme:
universal <-- I kind of like this! "minimal" -> "unique" -> "universal"
well-formed
precise
general
unrestricted

**Comment by jennybc** [comment]
Proposal, which will affect this PR and tibble:

  * minimal: names exist, blah blah blah

  * unique: names contain no duplicates, no empties. Every element is uniquely identified by its name.

  * universal: names are unique and syntactic. Names can be used anywhere, without quoting, without ambiguity.

Speak now or ...

**Comment by lionel-** [comment]
We're trying not to use "tidy" for everything but that's a case where tidy is actually meaningful and seems right. "tidy names" is more suggestive than "universal names".

I think it'll be less awkward to explain to beginners what tidy names are:

* Universal names are universal because they are unique and don't have special characters
* Tidy names are tidy because they are unique and don't have special characters

**Comment by jennybc** [comment]
The argument against "tidy" is that the names we are talking about right now still don't follow tidyverse naming conventions (http://style.tidyverse.org/syntax.html#object-names). And we are sort of hoping to make "tidy" mean that, but we have to tackle these basics first.

So, eventually I would hope we could offer: minimal < unique < ?universal? < tidy

**Comment by krlmlr** [comment]
It would be great to merge this soon. Are there any concerns?

**Pull request merged**
