### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff ;-)

One thing I recommend adding content-wise, is a mention of and/or a reference to  [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) in order to show R users that this is a general & old principle. Please let me know if I should _not_ try adding this here via a new PR.

### CODE REVIEW

**Comment by hadley** [comment]
Yes, mention of POLA would be great!

**Comment by katrinleinweber** [comment]
Will do, but in a different PR ;-)

**Comment by hadley** [comment]
Thanks!

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
